name: deploy documentation
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    name: deploy documentation
    runs-on: ubuntu-latest
    steps:
    - name: deploy documentation
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.DEPLOY_KEY }}
        script: ~/deploy_documentation.sh
